In [1]:
import numpy as np
import pandas as pd

In [2]:
flats = pd.read_csv('flats_cleaned.csv')
flats

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2992,3 BHK Flat in Sector 86 Gurgaon,flat,ansal heights 86,1.05,5541.0,1895.0,Super Built up area 1895(176.05 sq.m.),3,3,3,servant room,"Tower C, Sector 86 Gurgaon, Gurgaon, Haryana",9.0,North-East,Under Construction,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",Residential apartment for sell.Located in sect...,[],NaN,"['Safety4.5 out of 5', 'Lifestyle5 out of 5', ..."
2993,5 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,3.30,9984.0,3305.0,Super Built up area 3905(362.79 sq.m.)Built Up...,5,5,3+,servant room,"Sector 48 Gurgaon, Gurgaon, Haryana",4.0,NaN,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",5 bhk duplex penthouse in low rise building.Av...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...","['Management4 out of 5', 'Green Area4 out of 5..."
2994,3 BHK Flat in Sector 108 Gurgaon,flat,raheja vedaanta,0.95,5214.0,1822.0,Super Built up area 1822(169.27 sq.m.),3,3,3,others,"Sector 108 Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,NaN,3 bedroom flat with full woodwork. Ready to mo...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Management3 out of 5', 'Green Area4 out of 5..."
2995,3 BHK Flat in DLF Phase 3,flat,ambience lagoon,5.80,12500.0,4640.0,Built Up area: 3700 (343.74 sq.m.),3,4,3+,"pooja room,study room,servant room,others","Gurgaon, DLF Phase 3, Gurgaon, Haryana",9.0,North-East,10+ Year Old,"['Micromax moulsari avenue metro station', 'In...",Luxury condominium complex located on delhi gu...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Private Garden / Te...","['Management5 out of 5', 'Green Area5 out of 5..."
2996,4 BHK Flat in Sector 54 Gurgaon,flat,dlf the crest,11.00,35222.0,3123.0,Super Built up area 3123(290.14 sq.m.),4,6,3,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Ardee Mall', '...",Club & pool facing\r\nVrv air conditioning,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '5 Geys...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Management4 out of 5', 'Green Area4 out of 5..."

In [3]:
houses = pd.read_csv('house_cleaned.csv')
houses

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,4 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,5.50,30556.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3,"pooja room,study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, g block, dlf phase-1, gurga...","['10 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...",NaN
960,3 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,4.25,31481.0,1350.0,Plot area 150(125.42 sq.m.),3,2,3,study room,"DLF Phase 2, Gurgaon, Haryana",2.0,North,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...","Residential house, k block, dlf phase-2, gurga...",NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Safety5 out of 5', ..."
961,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,4.50,33333.0,1350.0,Plot area 150(125.42 sq.m.),3,3,2,"study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block 150 sq.Yds , dlf ph...","['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
962,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,3.25,33129.0,981.0,Plot area 109(91.14 sq.m.),3,3,3,study room,"Sector 26 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
963,3 Bedroom House for sale in Bissar,house,silverglades tarudhan valley golf resort,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others","Bissar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [4]:
df = pd.concat([flats,houses],ignore_index=True)

In [5]:
df = df.sample(df.shape[0],ignore_index=True)

In [6]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 37C Gurgaon,flat,apex our homes,0.33,3567.0,925.0,Super Built up area 925(85.94 sq.m.)Built Up a...,2,2,1,not available,"358, Sector 37C Gurgaon, Gurgaon, Haryana",3.0,West,1 to 5 Year Old,"['Elvedor Mall', 'MDS Public School', 'K.D. Ho...",This 2 bhk apartment is available for sale in ...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,0.90,4615.0,1950.0,Super Built up area 1950(181.16 sq.m.),3,4,3,servant room,"503, Sector 90 Gurgaon, Gurgaon, Haryana",4.0,South-West,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...","Shree vardhman flora in sector 90, gurgaon is ...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 23A Gurgaon,flat,radhakrishna society,0.55,5000.0,1100.0,Super Built up area 1100(102.19 sq.m.),2,2,1,not available,"4719 B/104, Sector 23A Gurgaon, Gurgaon, Haryana",1.0,West,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Hospital nearby park nearby school nearby dail...,"['1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Ligh...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3,2 Bedroom House for sale in DLF Phase 4,house,independent,1.39,11583.0,1200.0,Plot area 540(50.17 sq.m.)Built Up area: 1450 ...,2,2,1,store room,"DLF Phase 4, Gurgaon, Haryana",3.0,North-East,10+ Year Old,"['Dlf phase 1 metro station', 'Huda city centr...",Built up home north east facing in 60 sq yard ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 86 Gurgaon,flat,microtek greenburg,1.65,8707.0,1895.0,Super Built up area 1895(176.05 sq.m.),3,4,3,servant room,"Tower, Sector 86 Gurgaon, Gurgaon, Haryana",8.0,North-West,1 to 5 Year Old,"['SS Omnia Mall', 'National Highway 8', 'Dwark...",Located in the popular residential address of ...,"['9 Light', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [7]:
df.to_csv('gurgaon_properties.csv',index=False)